---
abstract: 'Process (and optionally store) karma points'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
  - 'Apocalypse <APOCAL@cpan.org>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Karma
no_index:
  directory:
    - t
    - xt
    - utils
recommends:
  DBI: 0
requires:
  Any::Moose: 0.15
  Moose: 2.0007
  MooseX::StrictConstructor: 0.16
  Mouse: 0.93
  MouseX::StrictConstructor: 0.02
  namespace::clean: 0.20
  perl: 5.010
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Text-Karma
  homepage: http://metacpan.org/release/Text-Karma
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/text-karma.git
version: 0.04
x_authority: cpan:HINRIK
